// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareImageSolution.Data;

namespace ShareImageSolution.Migrations
{
    [DbContext(typeof(ShareImageDbContext))]
    [Migration("20210516091630_UpdateRelation")]
    partial class UpdateRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareImageSolution.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggesstion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            NameCategory = "Thiên Nhiên",
                            Suggesstion = "Nhiều hơn về thiên nhiên"
                        },
                        new
                        {
                            CategoryId = 2,
                            NameCategory = "Động vật",
                            Suggesstion = "Nhiều hơn về động vật"
                        },
                        new
                        {
                            CategoryId = 3,
                            NameCategory = "Phong Cảnh",
                            Suggesstion = "Nhiều hơn về phong cảnh"
                        },
                        new
                        {
                            CategoryId = 4,
                            NameCategory = "Vũ Trụ",
                            Suggesstion = "Nhiều hơn về vũ trụ"
                        });
                });

            modelBuilder.Entity("ShareImageSolution.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownLoad")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            Alt = "Ảnh Cáo Tuyết Trắng",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 711, DateTimeKind.Local).AddTicks(931),
                            Description = "Con cáo tuyết đang nằm trên tuyết",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/CaoTuyet.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 2,
                            Alt = "Ảnh Con Bướm Xuân",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(819),
                            Description = "Con bướm vơn vởn cảnh hoa",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/butterfly.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 3,
                            Alt = "Ảnh Con Chim Đậu Cành Hoa ",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1022),
                            Description = "Con đang đậu trên cành hoa vào mùa xuân",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/ConChim.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 4,
                            Alt = "Ảnh Đỉnh Núi Thiên Nhiên",
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1031),
                            Description = "Đỉnh núi cao thật đẹp, sự sáng tạo của tự nhiên",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/DinhNui.png",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 5,
                            Alt = "Ảnh Phong Cảnh Thiên Nhiên",
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1036),
                            Description = "Phong cảnh thiên nhiên vào ban đêm, cây khô dưới ánh trăng",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/landscape.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 6,
                            Alt = "Ảnh Thiên Hà",
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1040),
                            Description = "Sự vẻ đẹp của vụ trụ thật là kỳ diệu",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/galaxy.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 7,
                            Alt = "Ảnh Rừng Cây Âm U",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1046),
                            Description = "Rừng cây âm u thiếu ánh sáng",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCayAmU.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 8,
                            Alt = "Ảnh Rừng Cây Màu Vàng",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1052),
                            Description = "Rừng cây vào mua thu",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCayMauVang.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 9,
                            Alt = "Ảnh Rừng Cây Đầy Sức Sống",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1057),
                            Description = "Lối đi vào rừng cây đầy sức sống",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCaySucSong.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 10,
                            Alt = "Ảnh Hoàng Hôn",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1061),
                            Description = "Hoàng hôn trên đồi núi",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/sunset.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 11,
                            Alt = "Ảnh Tảng Băng",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1065),
                            Description = "Tảng băng nổi trên biển",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/tangbang.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            ImageId = 12,
                            Alt = "Ảnh Phong Cảnh Cổ Xưa",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 16, 16, 16, 29, 713, DateTimeKind.Local).AddTicks(1069),
                            Description = "Bức tranh phong cảnh sơn mài thật đẹp",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/MayMu.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        });
                });

            modelBuilder.Entity("ShareImageSolution.Models.Image", b =>
                {
                    b.HasOne("ShareImageSolution.Models.Category", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
