// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareImageSolution.Data;

namespace ShareImageSolution.Migrations
{
    [DbContext(typeof(ShareImageDbContext))]
    [Migration("20210513143947_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareImageSolution.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownLoad")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "Ảnh Cáo Tuyết Trắng",
                            DateCreated = new DateTime(2021, 5, 13, 21, 39, 46, 527, DateTimeKind.Local).AddTicks(8203),
                            Description = "Con cái tuyết đang nằm trên tuyết",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/CaoTuyet.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 2,
                            Alt = "Ảnh Cáo Tuyết Trắng",
                            DateCreated = new DateTime(2021, 5, 13, 21, 39, 46, 529, DateTimeKind.Local).AddTicks(5233),
                            Description = "Con cái tuyết đang nằm trên tuyết",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/CaoTuyet.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 3,
                            Alt = "Ảnh Cực Quang ở Nam Cực",
                            DateCreated = new DateTime(2021, 5, 13, 21, 39, 46, 529, DateTimeKind.Local).AddTicks(5336),
                            Description = "Cực quang ở nam bán cầu, màu sắc trên bầu trời",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/cucquang.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 4,
                            Alt = "Ảnh Chim Đậu Cành Hoa",
                            DateCreated = new DateTime(2021, 5, 13, 21, 39, 46, 529, DateTimeKind.Local).AddTicks(5342),
                            Description = "Con chim đang đậu trên cành hoa vào mùa xuân",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/CaoTuyet.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
