// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareImageSolution.Data;

namespace ShareImageSolution.Migrations
{
    [DbContext(typeof(ShareImageDbContext))]
    [Migration("20210514111509_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShareImageSolution.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownLoad")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "Ảnh Cáo Tuyết Trắng",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 292, DateTimeKind.Local).AddTicks(5651),
                            Description = "Con cáo tuyết đang nằm trên tuyết",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/CaoTuyet.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 2,
                            Alt = "Ảnh Con Bướm Xuân",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3853),
                            Description = "Con bướm vơn vởn cảnh hoa",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/butterfly.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 3,
                            Alt = "Ảnh Con Chim Đậu Cành Hoa ",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3957),
                            Description = "Con đang đậu trên cành hoa vào mùa xuân",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/ConChim.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 4,
                            Alt = "Ảnh Đỉnh Núi Thiên Nhiên",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3962),
                            Description = "Đỉnh núi cao thật đẹp, sự sáng tạo của tự nhiên",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/DinhNui.png",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 5,
                            Alt = "Ảnh Phong Cảnh Thiên Nhiên",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3967),
                            Description = "Phong cảnh thiên nhiên vào ban đêm, cây khô dưới ánh trăng",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/landscape.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 6,
                            Alt = "Ảnh Thiên Hà",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3969),
                            Description = "Sự vẻ đẹp của vụ trụ thật là kỳ diệu",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/galaxy.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 7,
                            Alt = "Ảnh Rừng Cây Âm U",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3973),
                            Description = "Rừng cây âm u thiếu ánh sáng",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCayAmU.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 8,
                            Alt = "Ảnh Rừng Cây Màu Vàng",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3976),
                            Description = "Rừng cây vào mua thu",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCayMauVang.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 9,
                            Alt = "Ảnh Rừng Cây Đầy Sức Sống",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3978),
                            Description = "Lối đi vào rừng cây đầy sức sống",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/RungCaySucSong.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 10,
                            Alt = "Ảnh Hoàng Hôn",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3981),
                            Description = "Hoàng hôn trên đồi núi",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/sunset.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 11,
                            Alt = "Ảnh Tảng Băng",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3983),
                            Description = "Tảng băng nổi trên biển",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/tangbang.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        },
                        new
                        {
                            Id = 12,
                            Alt = "Ảnh Phong Cảnh Cổ Xưa",
                            DateCreated = new DateTime(2021, 5, 14, 18, 15, 8, 294, DateTimeKind.Local).AddTicks(3986),
                            Description = "Bức tranh phong cảnh sơn mài thật đẹp",
                            DownLoad = 50,
                            Path = "/Images/ImageForDetail/MayMu.jpg",
                            Size = "400x300",
                            Type = "jpg",
                            View = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
